# This file was generated by GoReleaser. DO NOT EDIT.
cask "pingcli" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "d7fa7a3d1f4e576015afb01372bfadaba35c35b48f19128b91c24909d196e83c"
      url "https://github.com/pingidentity/pingcli/releases/download/v#{version}/pingcli_#{version}_darwin_amd64"
      binary "pingcli_1.0.0_darwin_amd64", target: "pingcli"
    end
    on_arm do
      sha256 "ee4d6f72aa87dfb12b84707ff8d26c91f7ebcbff13685986131b2dd1a969d65d"
      url "https://github.com/pingidentity/pingcli/releases/download/v#{version}/pingcli_#{version}_darwin_arm64"
      binary "pingcli_1.0.0_darwin_arm64", target: "pingcli"
    end
  end

  on_linux do
    on_intel do
      sha256 "00dceb39301e207e0741125e9193adcff309f9a43552ee0a7f97bdb40577d87a"
      url "https://github.com/pingidentity/pingcli/releases/download/v#{version}/pingcli_#{version}_linux_amd64"
      binary "pingcli_1.0.0_linux_amd64", target: "pingcli"
    end
    on_arm do
      sha256 "fca6e873add25c9fffd2ba3e311dd36000a7c0afaa550ba896c8e1e0a2c95f78"
      url "https://github.com/pingidentity/pingcli/releases/download/v#{version}/pingcli_#{version}_linux_arm64"
      binary "pingcli_1.0.0_linux_arm64", target: "pingcli"
    end
  end

  name "pingcli"
  desc "The Ping CLI is a unified command line interface for configuring and managing Ping Identity Services."
  homepage "https://github.com/pingidentity/pingcli"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
