# This file was generated by GoReleaser. DO NOT EDIT.
cask "pingcli" do
  version "1.5.0"

  on_macos do
    on_intel do
      sha256 "cc7d329b4941e80a58ef5258edcea2c42baa48c4f415ff519c13770b93ced34e"
      url "https://github.com/pingidentity/pingcli/releases/download/v#{version}/pingcli_#{version}_darwin_amd64"
      binary "pingcli_1.5.0_darwin_amd64", target: "pingcli"
    end
    on_arm do
      sha256 "5193c4c4e72aceaff3a0693209a27e89018e57299bc861f314c377f67b6e24f2"
      url "https://github.com/pingidentity/pingcli/releases/download/v#{version}/pingcli_#{version}_darwin_arm64"
      binary "pingcli_1.5.0_darwin_arm64", target: "pingcli"
    end
  end

  on_linux do
    on_intel do
      sha256 "5d3529eb6bf15d10431e4a2989c27a0eeb19d23c17b648b1f92356ad348f6ee8"
      url "https://github.com/pingidentity/pingcli/releases/download/v#{version}/pingcli_#{version}_linux_amd64"
      binary "pingcli_1.5.0_linux_amd64", target: "pingcli"
    end
    on_arm do
      sha256 "44a51368168bfbe92a5012fdbbcb0efc31cd73d1c9d61ec833e1ba35733ce0bd"
      url "https://github.com/pingidentity/pingcli/releases/download/v#{version}/pingcli_#{version}_linux_arm64"
      binary "pingcli_1.5.0_linux_arm64", target: "pingcli"
    end
  end

  name "pingcli"
  desc "The Ping CLI is a unified command line interface for configuring and managing Ping Identity Services."
  homepage "https://github.com/pingidentity/pingcli"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
