# This file was generated by GoReleaser. DO NOT EDIT.
cask "pingcli" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "e4fca1965aac061a36533aa64cb4f887a52cd8cc7e490eb01d128ea184051eeb"
      url "https://github.com/pingidentity/pingcli/releases/download/v#{version}/pingcli_#{version}_darwin_amd64"
      binary "pingcli_1.1.0_darwin_amd64", target: "pingcli"
    end
    on_arm do
      sha256 "b6445ec218d88d88399e2f2a3a1b42038310774117be30525907f027a6628a69"
      url "https://github.com/pingidentity/pingcli/releases/download/v#{version}/pingcli_#{version}_darwin_arm64"
      binary "pingcli_1.1.0_darwin_arm64", target: "pingcli"
    end
  end

  on_linux do
    on_intel do
      sha256 "50a1f8101299a8df7b276165f43a0db27da15eb003bcef32fff9f286d0663884"
      url "https://github.com/pingidentity/pingcli/releases/download/v#{version}/pingcli_#{version}_linux_amd64"
      binary "pingcli_1.1.0_linux_amd64", target: "pingcli"
    end
    on_arm do
      sha256 "e1b379c3c7e4a8b1dd3be8b8ef03b116f0ddf8b9edbd8992fd32be4335c80913"
      url "https://github.com/pingidentity/pingcli/releases/download/v#{version}/pingcli_#{version}_linux_arm64"
      binary "pingcli_1.1.0_linux_arm64", target: "pingcli"
    end
  end

  name "pingcli"
  desc "The Ping CLI is a unified command line interface for configuring and managing Ping Identity Services."
  homepage "https://github.com/pingidentity/pingcli"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
