# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PingoneMcpServer < Formula
  desc "The PingOne MCP (Model Context Protocol) server enables AI assistants to review and manage PingOne tenants by integrating the PingOne management API to AI assistant conversations."
  homepage "https://github.com/pingidentity/pingone-mcp-server"
  version "0.0.1"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pingidentity/pingone-mcp-server/releases/download/v0.0.1/pingone-mcp-server_0.0.1_darwin_amd64"
      sha256 "57ea6a675cc8fbea88630b24637603f16a4bbff48eac27b3d6a2986870ae72b8"

      def install
        bin.install "pingone-mcp-server_0.0.1_darwin_amd64" => "pingone-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pingidentity/pingone-mcp-server/releases/download/v0.0.1/pingone-mcp-server_0.0.1_darwin_arm64"
      sha256 "dda264150642c256f36d7f574ed203d662be93af7451acc7c52eea7d298e1f58"

      def install
        bin.install "pingone-mcp-server_0.0.1_darwin_arm64" => "pingone-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pingidentity/pingone-mcp-server/releases/download/v0.0.1/pingone-mcp-server_0.0.1_linux_amd64"
      sha256 "d710e9749cbe1af5d6e923279c0f14da82a50da095f0bd0209995f50e531ee1d"
      def install
        bin.install "pingone-mcp-server_0.0.1_linux_amd64" => "pingone-mcp-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pingidentity/pingone-mcp-server/releases/download/v0.0.1/pingone-mcp-server_0.0.1_linux_arm64"
      sha256 "0b6f5b0e21ecd3be107ea3eb3b932580998a1adce6b2328a679e2607952054c6"
      def install
        bin.install "pingone-mcp-server_0.0.1_linux_arm64" => "pingone-mcp-server"
      end
    end
  end
end
