# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pingcli < Formula
  desc "The Ping CLI is a unified command line interface for configuring and managing Ping Identity Services."
  homepage "https://github.com/pingidentity/pingcli"
  version "1.3.0"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pingidentity/pingcli/releases/download/v1.3.0/pingcli_1.3.0_darwin_amd64"
      sha256 "66fa5ac7e76bfca2faa8c2761b75fec8d2fada598f49cec71efb6aa9e31176fc"

      define_method(:install) do
        bin.install "pingcli_1.3.0_darwin_amd64" => "pingcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pingidentity/pingcli/releases/download/v1.3.0/pingcli_1.3.0_darwin_arm64"
      sha256 "522b744b9f2c9fd055f4a9f43073b9f8e5830e361cf0d0c04d03dac0257f0580"

      define_method(:install) do
        bin.install "pingcli_1.3.0_darwin_arm64" => "pingcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pingidentity/pingcli/releases/download/v1.3.0/pingcli_1.3.0_linux_amd64"
      sha256 "1f050f9b65a1a7480a48e4377f096981d5afece99c63a19f94786b11e1a49753"
      define_method(:install) do
        bin.install "pingcli_1.3.0_linux_amd64" => "pingcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pingidentity/pingcli/releases/download/v1.3.0/pingcli_1.3.0_linux_arm64"
      sha256 "b0fcb0c32eb97152a1b2f3a12cc59b41ff20454488ebe07750ab9825e366c291"
      define_method(:install) do
        bin.install "pingcli_1.3.0_linux_arm64" => "pingcli"
      end
    end
  end
end
