# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PingcliPluginTerraformer < Formula
  desc "Ping CLI plugin for converting PingOne DaVinci flows to Terraform HCL"
  homepage "https://github.com/pingidentity/pingcli-plugin-terraformer"
  version "0.5.0"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pingidentity/pingcli-plugin-terraformer/releases/download/v0.5.0/pingcli-terraformer_0.5.0_darwin_amd64"
      sha256 "89e1ef88755bf02137845f60ccf8ae0596dde682f7519b9b7c6210bb9413504b"

      define_method(:install) do
        bin.install "pingcli-terraformer_0.5.0_darwin_amd64" => "pingcli-terraformer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pingidentity/pingcli-plugin-terraformer/releases/download/v0.5.0/pingcli-terraformer_0.5.0_darwin_arm64"
      sha256 "d37ddd3070b0edde06e703021af3c050e24189287dcac71c3fb0577b4e7e4ac2"

      define_method(:install) do
        bin.install "pingcli-terraformer_0.5.0_darwin_arm64" => "pingcli-terraformer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pingidentity/pingcli-plugin-terraformer/releases/download/v0.5.0/pingcli-terraformer_0.5.0_linux_amd64"
      sha256 "4813b56736595f9812602f28e5da088e91ad42697d8321c4b9e38e25de9449a7"
      define_method(:install) do
        bin.install "pingcli-terraformer_0.5.0_linux_amd64" => "pingcli-terraformer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pingidentity/pingcli-plugin-terraformer/releases/download/v0.5.0/pingcli-terraformer_0.5.0_linux_arm64"
      sha256 "480340c960546c172eda794f23e6ce16a4277c12b39f2b28a7788a86f6bbac5f"
      define_method(:install) do
        bin.install "pingcli-terraformer_0.5.0_linux_arm64" => "pingcli-terraformer"
      end
    end
  end
end
