# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PingoneMcpServer < Formula
  desc "The PingOne MCP (Model Context Protocol) server enables AI assistants to review and manage PingOne tenants by integrating the PingOne management API to AI assistant conversations."
  homepage "https://github.com/pingidentity/pingone-mcp-server"
  version "0.0.2"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pingidentity/pingone-mcp-server/releases/download/v0.0.2/pingone-mcp-server_0.0.2_darwin_amd64"
      sha256 "27ef27081bb30e153931e0b2046a03604b21ee806d69899b4353e54769a84e73"

      def install
        bin.install "pingone-mcp-server_0.0.2_darwin_amd64" => "pingone-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pingidentity/pingone-mcp-server/releases/download/v0.0.2/pingone-mcp-server_0.0.2_darwin_arm64"
      sha256 "7b1203722d7a60eb5ed80f5318e750abcb5e46651b528ce65d006f290f56d757"

      def install
        bin.install "pingone-mcp-server_0.0.2_darwin_arm64" => "pingone-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pingidentity/pingone-mcp-server/releases/download/v0.0.2/pingone-mcp-server_0.0.2_linux_amd64"
      sha256 "d19f8c987c581b6b7551628b4b564ecc4122ff9105407e2f717b9b45f2a912bb"
      def install
        bin.install "pingone-mcp-server_0.0.2_linux_amd64" => "pingone-mcp-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pingidentity/pingone-mcp-server/releases/download/v0.0.2/pingone-mcp-server_0.0.2_linux_arm64"
      sha256 "9ae7ffac5639a7bfc820386f4a1d6b5947550a5686dad87ec2432dbc3baf5131"
      def install
        bin.install "pingone-mcp-server_0.0.2_linux_arm64" => "pingone-mcp-server"
      end
    end
  end
end
