# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PingcliPluginTerraformer < Formula
  desc "Ping CLI plugin for converting PingOne DaVinci flows to Terraform HCL"
  homepage "https://github.com/pingidentity/pingcli-plugin-terraformer"
  version "0.2.0"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pingidentity/pingcli-plugin-terraformer/releases/download/v0.2.0/pingcli-terraformer_0.2.0_darwin_amd64"
      sha256 "e71679b34a888c28e178209a8db143cb43f077e1b70cad11775b6d8734ce3ed6"

      define_method(:install) do
        bin.install "pingcli-terraformer_0.2.0_darwin_amd64" => "pingcli-terraformer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pingidentity/pingcli-plugin-terraformer/releases/download/v0.2.0/pingcli-terraformer_0.2.0_darwin_arm64"
      sha256 "0eda5153a0c4dfcea0c564d93894f6ea399ec9b498b793f9c237408308046b12"

      define_method(:install) do
        bin.install "pingcli-terraformer_0.2.0_darwin_arm64" => "pingcli-terraformer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pingidentity/pingcli-plugin-terraformer/releases/download/v0.2.0/pingcli-terraformer_0.2.0_linux_amd64"
      sha256 "9d2b6ad9b02297c99db6a7c76f494af92ee99409a9a8bf481559863a2bda6572"
      define_method(:install) do
        bin.install "pingcli-terraformer_0.2.0_linux_amd64" => "pingcli-terraformer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pingidentity/pingcli-plugin-terraformer/releases/download/v0.2.0/pingcli-terraformer_0.2.0_linux_arm64"
      sha256 "64efd15da796581802d96b03f9d7c4f5a52b7d4c14ab48a0ac61de5c1af5e1a2"
      define_method(:install) do
        bin.install "pingcli-terraformer_0.2.0_linux_arm64" => "pingcli-terraformer"
      end
    end
  end
end
