# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PingoneMcpServer < Formula
  desc "The PingOne MCP (Model Context Protocol) server enables AI assistants to review and manage PingOne tenants by integrating the PingOne management API to AI assistant conversations."
  homepage "https://github.com/pingidentity/pingone-mcp-server"
  version "0.0.1"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pingidentity/pingone-mcp-server/releases/download/v0.0.1/pingone-mcp-server_0.0.1_darwin_amd64"
      sha256 "3e839ff0c32a085290dd5d6c98043dd7cd4f93145c858057501f9d36320fbbb6"

      def install
        bin.install "pingone-mcp-server_0.0.1_darwin_amd64" => "pingone-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pingidentity/pingone-mcp-server/releases/download/v0.0.1/pingone-mcp-server_0.0.1_darwin_arm64"
      sha256 "2f8c00a73603821fe84aa1c06116c9bfb76399d89c611de91b61cbed21e3c418"

      def install
        bin.install "pingone-mcp-server_0.0.1_darwin_arm64" => "pingone-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pingidentity/pingone-mcp-server/releases/download/v0.0.1/pingone-mcp-server_0.0.1_linux_amd64"
      sha256 "c1ccee233d81332d9c7298eb1d7ebd9c103a75ff58149f431bb818453b27663a"
      def install
        bin.install "pingone-mcp-server_0.0.1_linux_amd64" => "pingone-mcp-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pingidentity/pingone-mcp-server/releases/download/v0.0.1/pingone-mcp-server_0.0.1_linux_arm64"
      sha256 "e9c245409a1ac23e53357b4d8d7dfddaaef8ab7bb5f1bb3a9ce829362244afa4"
      def install
        bin.install "pingone-mcp-server_0.0.1_linux_arm64" => "pingone-mcp-server"
      end
    end
  end
end
